### ISSUE TITLE
Ansible community.rabbitmq can't use RABBITMQ_USE_LONGNAME

### ISSUE THREAD

**Issue by kost1993** [ansible-collections/community.rabbitmq#109]
##### SUMMARY
There is a problem with cluster which uses longnames in rabbitmq cluster. For now there is no possible way to use any play against such clusters. There is no such option in plugins and possible life hacks such as setting remote environment doesn’t work.
For instance: rabbitmqctl can be used in bash with longnames:
```
sudo RABBITMQ_USE_LONGNAME=true RABBITMQ_NODENAME=rabbit@something.domain.net rabbitmqctl ...
or
sudo rabbitmqctl --longnames --node=rabbit@something.domain.net ...
```
But in the rabbitmq_user.py of ansible collection there is no possible way to use such option for longnames.
In definition `_exec`
https://github.com/ansible-collections/community.rabbitmq/blob/65b0022243af0780a91480f18f019eada432eb86/plugins/modules/rabbitmq_user.py#L285
it can use flag `--node` but not `--longnames`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
```
rabbitmq_user
rabbitmq_vhost
```

##### ANSIBLE VERSION

```
ansible --version

ansible [core 2.11.6]
  config file = /home/k_ilyasov/ansible.cfg
  configured module search path = ['/home/k_ilyasov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/k_ilyasov/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.2
  libyaml = True
```

##### COLLECTION VERSION

```
ansible-galaxy collection list community.rabbitmq

# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection         Version
------------------ -------
community.rabbitmq 1.1.0
```

##### CONFIGURATION

```paste below
Default configuration
```

##### OS / ENVIRONMENT

OS: Debian 11

##### STEPS TO REPRODUCE

```
- block:
  - name: "delete default user guest"
    community.rabbitmq.rabbitmq_user:
      user: guest
      state: absent
    environment:
      RABBITMQ_USE_LONGNAME: "true"
      RABBITMQ_NODENAME: "{{ rabbitmq_node_name }}"
    vars:
      rabbitmq_node_name: "rabbit@something.domain.net"
```

##### EXPECTED RESULTS

Users should be created or deleted.

##### ACTUAL RESULTS

Playbook failed.

```paste below
TASK [rabbitmq-server : delete default user guest] *********************************************************************
fatal: [testrmq01]: FAILED! => {"changed": false, "msg": "Could not determine the version of the RabbitMQ server."}
```
