### ISSUE TITLE
Allow to specify queue type in rabbitmq_queue module

### ISSUE THREAD

**Issue by wrobell** [ansible-collections/community.rabbitmq#114]
RabbitMQ has various types of queues

- classic
- quorum
- stream (since 3.9.x)

It would be great if we could specify queue type via rabbitmq_queue module.

**Comment by Andersson007** [comment]
@wrobell hello and welcome to the project!
Thanks for the issue! I've put the `help_wanted` label, so interested folks can pick it up

**Comment by DavidLevayer** [comment]
You can do it using the `arguments` parameter:

```yaml
- name: create quorum queue
      community.rabbitmq.rabbitmq_queue:
        name: quorum_queue
        login_user: guest
        login_password: guest
        login_host: localhost
        arguments:
          x-queue-type: quorum
```

**Comment by wrobell** [comment]
I have finally found some time to revisit this.

@DavidLevayer I did try using the `arguments` parameter in the past, but it failed with an error.

After further investigation, this works:
```
    - name: Create RabbitMQ stream
      become: yes
      community.rabbitmq.rabbitmq_queue:
        name: test-x
        arguments:
          x-queue-type: stream
          x-max-age: 24h
```

Changing queue name to contain slash like
```
    - name: Create RabbitMQ stream
      become: yes
      community.rabbitmq.rabbitmq_queue:
        name: test-x/test-y
        arguments:
          x-queue-type: stream
          x-max-age: 24h
```
fails with error
```
Invalid response from RESTAPI when trying to check if queue exists
```
Using `rabbitmqadmin declare queue` I can create `test-x/test-y` stream, so it seems like there is a problem with the Ansible plugin.

Also, I believe, it would be worth having high-level queue type parameter for the plugin. If not, that's OK and I can close this ticket and open new one for the problem above.
