### ISSUE TITLE
Cannot create exchange of type "x-random"

### ISSUE THREAD

**Issue by DavidLevayer** [ansible-collections/community.rabbitmq#123]
##### SUMMARY
`rabbitmq_exchange` module does not allow to create exchanges of type `x-random` (allowed by core [rabbitmq_random_exchange](https://github.com/rabbitmq/rabbitmq-server/tree/b62c5499cefa2f57d8516f3948543383d8387d4b/deps/rabbitmq_random_exchange) plugin).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```
rabbitmq_exchange
```

##### ANSIBLE VERSION

```paste below
ansible 2.10.17
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
community.rabbitmq 1.0.1
```

##### STEPS TO REPRODUCE

```yaml
# Rabbitmq plugin "rabbitmq_random_exchange" must be enabled on Rabbitmq node

- name: Create monitoring exchanges
  community.rabbitmq.rabbitmq_exchange:
    name: my_exchange
    exchange_type: x-random
    login_host: "{{ rabbitmq_host }}"
    login_user: "{{ rabbitmq_login_user }}"
    login_password: "{{ rabbitmq_login_password }}"
```

##### EXPECTED RESULTS

Exchanges are created if type is valid at runtime.

##### ACTUAL RESULTS

Got following error:

```paste below
value of exchange_type must be one of: fanout, direct, headers, topic, got: x-random
```
Looks like the module performs some checks, but it should either:
* have all valid values
* let Rabbitmq node itself decide if exchange type is valid or not
