### ISSUE TITLE
Publushing works with queues, not with exchanges

### ISSUE THREAD

**Issue by alexdjachenko** [ansible-collections/community.rabbitmq#138]
##### SUMMARY
All examples of rabbitmq_publish demonstate only publishing to  queue, but main publishing method in rabbitmq should work with exchanges. Becouse only exchanges could me configurate for routing.
There is options "exchanges", but it doesn't work: when I try publish message to exchange without queue, it post it to random queue and routing is ignored.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
rabbitmq_publish

##### ANSIBLE VERSION

```paste below
My Ansible is 2.9.7, but judging by the documentations and examples nobody think that publishing to exchange point is main method, but publushing direct to queue is very strange special case.
```

##### STEPS TO REPRODUCE

```yaml
    - name: Publish a message to a queue
      community.rabbitmq.rabbitmq_publish:
        url: "{{ amqp_url }}"
        exchange: 'myexchange'
        body: "Hello world from ansible module rabbitmq_publish 1"
        content_type: "text/plain"
        durable: yes
```

##### EXPECTED RESULTS

Message in 'myexchange' exchange point and routing it to queue by preset rules.

##### ACTUAL RESULTS

Message in random queue without any routing

**Comment by Im0** [comment]
@alexdjachenko thanks for raising this.  You are completely right,  it appears that I missed out the code for sending messages to an exchange!  I've not used rabbit in a while but I will take a look.

**Comment by Im0** [comment]
@alexdjachenko this probably needs a bit of a tidy up, but, I've tested rabbitmq by creating a exchange (`test_exchange`) which fans out to two queues (`queue1` & `queue2`).  By specifying an empty queue with an exchange the module then does not create a random queue and utilises the exchange.

```
- name: Testing publishing to rabbitmq exchanges
  hosts: localhost
  gather_facts: no
  tasks:
    - name: RabbitMQ to exchange
      community.rabbitmq.rabbitmq_publish:
        exchange: test_exchange
        queue: ""
        url: "amqp://guest:guest@172.16.10.10:5672/%2F"
        body: "Hello world exchange from ansible module rabbitmq_publish"
        content_type: "text/plain"
```
I'll have a look at how to make it a bit more user friendly. :)
