### ISSUE TITLE
Declare default queue type when creating a new virtual host

### ISSUE THREAD

**Issue by zenhighzer** [ansible-collections/community.rabbitmq#166]
##### SUMMARY
Declare default queue type when creating a new virtual host

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
rabbitmq_vhost module

##### ADDITIONAL INFORMATION
RabbitMQ Docs: 
https://rabbitmq-website.pages.dev/docs/vhosts#default-queue-type

Maybe an ansible-example could look like this: 
```
- name: Ensure that the vhost /test exists.
  community.rabbitmq.rabbitmq_vhost:
    name: /test
    state: present
    default_queue_type: "quorum" 

```
