### ISSUE TITLE
Support all option in rabbitmq_feature_flag module

### ISSUE THREAD

**Issue by jovial** [ansible-collections/community.rabbitmq#169]
##### SUMMARY
Currently you can't do:

```
- name: Enable all feature flags on 'rabbit@node-1'
  community.rabbitmq.rabbitmq_feature_flag:
    name: all
    node: rabbit@node-1
```

As shown here:

https://www.rabbitmq.com/docs/upgrade#enable-required-feature-flags-before-attempting-the-upgrade

Since we check for the current state of the 'all' feature and this comes back as unavailable. It would be nice if we special cased the all feature to not perform this check.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

rabbitmq_feature_flag module

##### ADDITIONAL INFORMATION

```yaml

```
