### ISSUE TITLE
Add an option to allow rabbitmq_vhost to use API for managing users

### ISSUE THREAD

**Issue by Thorsieger** [ansible-collections/community.rabbitmq#171]
##### SUMMARY
Feature request similar to https://github.com/ansible-collections/community.rabbitmq/issues/76 : rabbitmq_vhost uses `rabbitmqctl` for managing users. The idea is to add a choice for allowing to use API as well.

##### ISSUE TYPE
- Feature Idea :

Managing exchanges, queues, bindings and user can be perform using rabbitmq API. It will be nice to have the same for vhosts.

##### COMPONENT NAME
https://github.com/ansible-collections/community.rabbitmq/blob/main/plugins/modules/rabbitmq_vhost.py

##### ADDITIONAL INFORMATION

Using the documentation, the configuration could looks like this :

```yaml
- name: Ensure that the vhost /test exists.
  community.rabbitmq.rabbitmq_vhost:
    name: /test
    state: present
    provider: api
    login_user: user
    login_password: secret
    login_host: remote.example.org
```
