### ISSUE TITLE
Add an option to allow `rabbitmq_policy` to use management API for managing policies

### ISSUE THREAD

**Issue by dmbuck32** [ansible-collections/community.rabbitmq#203]
##### SUMMARY
Feature request similar to #76 & #171: `rabbitmq_policy` currently uses `rabbitmqctl` to manage policies. This feature request adds the choice for allowing the module to interface with the management API.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`rabbitmq_policy`

##### ADDITIONAL INFORMATION
This would allow for managing the rabbitmq policies through the management API. 

An example config:
```yaml
- name: Ensure the default vhost contains the HA policy using REST APIs.
  community.rabbitmq.rabbitmq_policy:
    name: HA
    pattern: .*
    login_host: remote.example.org
    login_user: admin
    login_password: changeadmin
    tags:
        ha-mode: all
```
