### ISSUE TITLE
The `rabbitmq_user` module fails to update user permissions when a vhost contains a `/`.

### ISSUE THREAD

**Issue by dmbuck32** [ansible-collections/community.rabbitmq#205]
##### SUMMARY
The `rabbitmq_user` module fails to update user permissions when a vhost contains a `/`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`rabbitmq_user.py`

##### ANSIBLE VERSION
```
ansible [core 2.19.0.dev0]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/community.rabbitmq/~/.venvs/ansible/lib/python3.12/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/community.rabbitmq/~/.venvs/ansible/bin/ansible
  python version = 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] (/home/user/community.rabbitmq/~/.venvs/ansible/bin/python)
  jinja version = 3.1.6
  pyyaml version = 6.0.2 (with libyaml v0.2.5)
```

##### COLLECTION VERSION
```
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.

# /home/user/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -----------
community.rabbitmq                       1.4.0

# /home/user/community.rabbitmq/~/.venvs/ansible/lib/python3.12/site-packages/ansible/_internal/ansible_collections
Collection                               Version
---------------------------------------- -----------
ansible._protomatter                     2.19.0.dev0
```

##### CONFIGURATION
```
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under development. This is a rapidly changing source of code and can become unstable at any point.
CONFIG_FILE() = None

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT
Ubuntu Noble

##### STEPS TO REPRODUCE
```yaml
- name: Configure the vhost
  community.rabbitmq.rabbitmq_vhost:
    name: "{{ vhost.key }}"
    state: "{{ vhost.value.state }}"
    tracing: "{{ vhost.value.tracing | default(omit) }}"

    # API params
    login_user: "{{ rabbitmq_admin_user }}"
    login_password: "{{ rabbitmq_admin_password }}"
    login_port: "{{ (rabbitmq_login_protocol == 'http') | ansible.builtin.ternary(rabbitmq_management_port, rabbitmq_management_port_ssl) }}"
    login_protocol: "{{ rabbitmq_login_protocol }}"
    login_host: "{{ ansible_fqdn }}"
  loop: "{{ rabbitmq_vhosts | dict2items }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.key }}"
  vars:
    rabbitmq_vhosts:
      "/test":
        state: present
    rabbitmq_management_port_ssl: 15671
    rabbitmq_management_port: 15672
    rabbitmq_login_protocol: https

- name: Add user account
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_user.value.username }}"
    password: "{{ rabbitmq_user.value.password }}"
    state: "{{ rabbitmq_user.value.state | default('present') }}"
    tags: "{{ rabbitmq_user.value.tags | default(omit) }}"
    vhost: "{{ rabbitmq_user.value.vhost | default(omit) }}"
    configure_priv: "{{ rabbitmq_user.value.configure_priv | default(omit) }}"
    read_priv: "{{ rabbitmq_user.value.read_priv | default(omit) }}"
    write_priv: "{{ rabbitmq_user.value.write_priv | default(omit) }}"
    update_password: always

    # API params
    login_user: "{{ rabbitmq_admin_user }}"
    login_password: "{{ rabbitmq_admin_password }}"
    login_port: "{{ (rabbitmq_login_protocol == 'http') | ansible.builtin.ternary(rabbitmq_management_port, rabbitmq_management_port_ssl) }}"
    login_protocol: "{{ rabbitmq_login_protocol }}"
    login_host: "{{ ansible_fqdn }}"
  loop: "{{ rabbitmq_users | dict2items }}"
  loop_control:
    loop_var: rabbitmq_user
    label: "{{ rabbitmq_user.key }}"
  vars:
    rabbitmq_users:
      "test":
        username: user
        password: password
        state: present
        tags: ""
        vhost: "/test"
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
    rabbitmq_management_port_ssl: 15671
    rabbitmq_management_port: 15672
    rabbitmq_login_protocol: https
```

##### EXPECTED RESULTS
The user permissions to be added.

##### ACTUAL RESULTS
The user failed to be added with the error code 405:
```
TASK [Configure the vhost] *****************************************************
changed: [rabbitmq-mq1] => (item=/test)

TASK [Add user account] ********************************************************
failed: [rabbitmq-mq1] (item=test) => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "ansible_loop_var": "rabbitmq_user", "changed": false, "msg": "Error trying to add permission to user user in rabbitmq. Status code '405'.", "rabbitmq_user": {"key": "test", "value": {"configure_priv": ".*", "password": "password", "read_priv": ".*", "state": "present", "tags": "", "username": "user", "vhost": "/test", "write_priv": ".*"}}}
```
