### ISSUE TITLE
Cannot use exchange type `x-delayed-message`

### ISSUE THREAD

**Issue by RolT** [ansible-collections/community.rabbitmq#54]
##### SUMMARY
Hello, the `rabbitmq_exchange` module does not accept the `x-delayed-message` type. It used to work in version 0.1.0.
The delayed message exchange is a rabbitmq plugin: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
rabbitmq_exchange

##### ANSIBLE VERSION
```
ansible 2.10.4
  config file = /home/rolandthiolliere/.ansible/conf.cfg
  configured module search path = ['/home/rolandthiolliere/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rolandthiolliere/anaconda3/lib/python3.8/site-packages/ansible
  executable location = /home/rolandthiolliere/anaconda3/bin/ansible
  python version = 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
```

##### CONFIGURATION
```ANSIBLE_SSH_CONTROL_PATH(/home/rolandthiolliere/.ansible/conf.cfg) = %(directory)s/%%h-%%p-%%r
DEFAULT_ROLES_PATH(/home/rolandthiolliere/.ansible/conf.cfg) = ['/home/rolandthiolliere/.ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/rolandthiolliere/.ansible/vault_password_file
INTERPRETER_PYTHON(/home/rolandthiolliere/.ansible/conf.cfg) = /usr/bin/env python
```

##### OS / ENVIRONMENT
Ubuntu 20.04.1 LTS

##### STEPS TO REPRODUCE
```yaml
  - name: Create the rabbitmq exchange
    rabbitmq_exchange:
      name: myapp
      type: x-delayed-message
      arguments:
        x-delayed-type: direct
      vhost: "{{ rb_vhost }}"
      login_host: "{{ rb_host }}"
      login_port: "{{ rb_port }}"
      login_protocol: "{{ rb_protocol }}"
      login_user: "{{ rb_admin_user }}"
      login_password: "{{ rb_admin_password }}"
      state: present
```

##### EXPECTED RESULTS
rabbitmq exchange created

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of exchange_type must be one of: fanout, direct, headers, topic, got: x-delayed-message"}
```

This can be solved by simply allowing `x-delayed-message` as a valid type and I can provide the PR is you want (tested locally), but that may not be the cleanest solution.
