### ISSUE TITLE
Add an option to allow rabbitmq_user to use API for managing users

### ISSUE THREAD

**Issue by seocam** [ansible-collections/community.rabbitmq#76]
##### SUMMARY
Currently rabbitmq_user uses `rabbitmqctl` for managing users. The idea is to add a choice for allowing to use API as well.

##### ISSUE TYPE

- Other plays in this collection already support using the API (like for managing exchanges, queues and bindings). My proposal is to add the option of using API for users as well without breaking backwards compatibility with the current implementation. 

The is to use providers to allow implementations to be kept and maintained apart from each other. I've done that before in the certifica role from linux system roles (https://github.com/linux-system-roles/certificate/). 

I would probably turn `module_utils/rabbitmq.py` in a package and add a directory providers inside it. The contents of rabbitmq.py could stay inside the package __init__.py.

##### ADDITIONAL INFORMATION

Using the 2 examples of the documentation that's how it would look:

```yaml
# Add user to server and assign full access control on / vhost.
# The user might have permission rules for other vhost but you don't care.
- community.rabbitmq.rabbitmq_user:
    user: joe
    password: changeme
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    provider: api
    login_user: user
    login_password: secret
    login_host: remote.example.org

# Add user to server and assign full access control on / vhost.
# The user doesn't have permission rules for other vhosts
- community.rabbitmq.rabbitmq_user:
    user: joe
    password: changeme
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
    provider: api
    login_user: user
    login_password: secret
    login_host: remote.example.org
 ```

**Comment by seocam** [comment]
At @libercapital we already implemented a way of using API for managing users and permissions. So we would only need to refactor the code to add it to the community repo. 

Let me know if you like the idea so we can start to work on a PR.

**Comment by seocam** [comment]
@Andersson007 @odyssey4me if you give us your "bless" we can start to work on it ;)

**Comment by Andersson007** [comment]
@seocam hi, thanks for the issue and mentioning! The idea sounds reasonable to me (especially that it will not break anything from the current functionality).

Though I'm not a specialist in rabbitmq, so it's a bit hard to judge (did just regular stuff related to the collection maintenance) but as we can see by the thumbs ups, it's worth doing it.

Maybe this [Quick-start guide](https://github.com/ansible/community-docs/blob/main/create_pr_quick_start_guide.rst) will help  and the [review checklist](https://github.com/ansible/community-docs/blob/main/review_checklist.rst) that we made recently. 

Even if you an experienced developer, I think there are some important points mentioned there which can help.

For people who'd like to test the future PR locally, there is also a [guide](https://github.com/ansible/community-docs/blob/main/test_pr_locally_guide.rst) for that.

Thank you

**Comment by seocam** [comment]
Roger that!

**Comment by msven** [comment]
@seocam Any update on this?

**Comment by Andersson007** [comment]
@msven if you have your own implementation, feel free to propose and thanks for pinging the issue author!:)

**Comment by seocam** [comment]
We actually did implement a bunch of features using the API. It's already in production for a few months for us.
We just didn't have the time to clean it up to create the PR.
CC: @arloc @gonzula

**Comment by dkossako** [comment]
@seocam may I help you somehow with that?

**Comment by seocam** [comment]
@dkossako we are organizing ourselves to create a PR without the tests and docs. From there I believe you will be able to help.

**Comment by nycterent** [comment]
same for vhosts would be nice. in general - i would like to use ansible community.rabbitmq to manage vhosts and users on amazon-mq service

**Comment by seocam** [comment]
> same for vhosts would be nice. in general - i would like to use ansible community.rabbitmq to manage vhosts and users on amazon-mq service

That was exactly my initial use case

**Comment by Im0** [comment]
@seocam thanks for sharing!  I'll try and give this a test soon and see if we can get this moving.

**Comment by Im0** [comment]
@seocam nice work,  I like it.  I did a few tests and the only issue I found was missing arguement `provider`.

When trying the example provided:

```
- community.rabbitmq.rabbitmq_user:
    user: joe
    password: changeme
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    provider: api
    login_user: user
    login_password: secret
    login_host: remote.example.org
```
I received:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (community.rabbitmq.rabbitmq_user) module: provider. Supported parameters include: state, login_protocol, tags, update_password, password, user (name, username), write_priv, login_password, read_priv, force, login_user, topic_permissions, configure_priv, login_host, vhost, node, permissions, login_port."}
```

Perhaps:
1. `provider=dict(type='str', default="rabbitctl", choices=["api", "rabbitctl"])` or similar in args… 
2. Requires check:  `if provider==api` ensure the `login_*` arguments are provided.
3. Then change the if statements check for `provider==api` instead of login details
4. Document string for provider, default being rabbitctl

Does that sound reasonable?
